#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 21 00:35:18 2019

@author: poss
"""

REFERENCE_POOL_ID="REFERENCEPOOLID"
LOAN_IDENTIFIER="LOANIDENTIFIER"
MONTHLY_REPORTING_PERIOD="MONTHLYREPORTINGPERIOD"
SELLER_NAME="SELLERNAME"
SERVICER_NAME="SERVICERNAME"
MASTER_SERVICER="MASTERSERVICER"
ORIGINAL_INTEREST_RATE="ORIGINALINTERESTRATE"
CURRENT_INTEREST_RATE="CURRENTINTERESTRATE"
ORIGINAL_UPB="ORIGINALUPB"
UPB_AT_ISSUANCE="UPBATISSUANCE"
CURRENT_ACTUAL_UPB="CURRENTACTUALUPB"
ORIGINAL_LOAN_TERM="ORIGINALLOANTERM"
ORIGINATION_DATE="ORIGINATIONDATE"
DEAL_NAME="DEALNAME"