#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 21 00:35:18 2019

@author: poss
"""

REFERENCE_POOL_ID="REFERENCE POOL ID"
LOAN_IDENTIFIER="LOAN IDENTIFIER"
MONTHLY_REPORTING_PERIOD="MONTHLY REPORTING PERIOD"
SELLER_NAME="SELLER NAME"
SERVICER_NAME="SERVICER NAME"
MASTER_SERVICER="MASTER SERVICER"
ORIGINAL_INTEREST_RATE="ORIGINAL INTEREST RATE"
CURRENT_INTEREST_RATE="CURRENT INTEREST RATE"
ORIGINAL_UPB="ORIGINAL UPB"
UPB_AT_ISSUANCE="UPB AT ISSUANCE"
CURRENT_ACTUAL_UPB="CURRENT ACTUAL UPB"
ORIGINAL_LOAN_TERM="ORIGINAL LOAN TERM"
ORIGINATION_DATE="ORIGINATION DATE"
DEAL_NAME="DEAL NAME"